#!/usr/bin/env python3
"""Phase-1 AGE loader: graph.json -> openCypher load script for Apache AGE.

Emits idempotent MERGE-on-id statements (per the deterministic identity rule) that
load the deterministic graph into the `codegraph` AGE graph created by
schema/age_schema.sql. Re-running the same SHA is a no-op (MERGE on id). The output
load.cypher is what feeds the AGE go/no-go benchmark (gate G7) on real shape.

Usage: python3 load_age.py            # writes loader/load.cypher
Then : psql "<conn>" -f ../schema/age_schema.sql && psql "<conn>" -f load.cypher
"""
import json, os

BASE = os.path.dirname(__file__)
G = json.load(open(os.path.join(BASE, "..", "graph", "graph.thin-slice.json")))
NODE = {n["id"]: n for n in G["nodes"]}

def lit(v):
    if v is None: return "null"
    return "'" + str(v).replace("\\", "\\\\").replace("'", "\\'") + "'"

def props(d, keys):
    return ", ".join(f"{k}: {lit(d.get(k))}" for k in keys if d.get(k) is not None)

NODE_PROPS = ["id","name","kind","stereotype","provenance","confidence","evidence",
              "source_ref","index_version","http_method","path"]
EDGE_PROPS = ["id","provenance","confidence","evidence","source_ref","index_version",
              "call_site","weave_kind"]

def cypher_stmt(inner):
    return f"SELECT * FROM cypher('codegraph', $$ {inner} $$) AS (v agtype);"

def main():
    out = []
    out.append("-- generated by load_age.py — idempotent MERGE-on-id load")
    out.append("LOAD 'age'; SET search_path = ag_catalog, \"$user\", public;\n")
    out.append("-- nodes")
    for nid in sorted(NODE):
        n = NODE[nid]
        out.append(cypher_stmt(
            f"MERGE (x:{n['label']} {{id: {lit(n['id'])}}}) SET x = {{{props(n, NODE_PROPS)}}}"))
    out.append("\n-- edges (endpoints already merged above, so MATCH then MERGE)")
    for e in sorted(G["edges"], key=lambda e: e["id"]):
        inner = (f"MATCH (a {{id: {lit(e['src'])}}}), (b {{id: {lit(e['dst'])}}}) "
                 f"MERGE (a)-[r:{e['type']} {{id: {lit(e['id'])}}}]->(b) "
                 f"SET r = {{{props(e, EDGE_PROPS)}}}")
        out.append(cypher_stmt(inner))
    path = os.path.join(BASE, "load.cypher")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {path}: {len(NODE)} node MERGEs + {len(G['edges'])} edge MERGEs")
    # quick well-formedness checks
    stmts = [l for l in out if l.startswith("SELECT")]
    assert all(l.count("$$") == 2 and l.rstrip().endswith(";") for l in stmts), "malformed cypher"
    print(f"validated {len(stmts)} cypher statements (balanced $$, terminated)")

if __name__ == "__main__":
    main()
