package com.att.rif.extractor.common;

import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.FieldDeclaration;
import com.github.javaparser.ast.expr.AnnotationExpr;
import java.util.Map;
import java.util.Set;

/**
 * Utility for detecting and filtering Lombok-generated code.
 *
 * <p>Lombok generates fields and methods that don't have explicit source declarations.
 * This utility helps Phase-2 extractors skip generated fields to reduce noise in DI/AOP
 * analysis (e.g., the `log` field generated by @Slf4j has no AST node and produces
 * spurious resolution failures).
 */
public class LombokUtil {

    // Lombok annotations that generate fields/methods
    private static final Set<String> LOMBOK_FIELD_GENERATORS = Set.of(
            "Data", "Value", "Getter", "Setter", "Builder",
            "NoArgsConstructor", "AllArgsConstructor", "RequiredArgsConstructor",
            "EqualsAndHashCode", "ToString", "With",
            "Slf4j", "Log", "Log4j", "Log4j2", "CommonsLog", "XSlf4j", "Flogger", "CustomLog"
    );

    // Fields generated by specific annotations
    private static final Map<String, Set<String>> GENERATED_FIELDS = Map.ofEntries(
            Map.entry("Slf4j", Set.of("log")),
            Map.entry("Log", Set.of("log")),
            Map.entry("Log4j", Set.of("log")),
            Map.entry("Log4j2", Set.of("log")),
            Map.entry("CommonsLog", Set.of("log")),
            Map.entry("XSlf4j", Set.of("log")),
            Map.entry("Flogger", Set.of("logger")),
            Map.entry("CustomLog", Set.of("log"))
    );

    private LombokUtil() {
    }

    /**
     * Check if a class has any Lombok annotations that generate fields.
     */
    public static boolean hasLombokFieldGenerators(ClassOrInterfaceDeclaration cls) {
        for (AnnotationExpr ann : cls.getAnnotations()) {
            String annName = ann.getNameAsString();
            if (LOMBOK_FIELD_GENERATORS.contains(annName)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Check if a field is likely generated by Lombok (e.g., @Slf4j log field).
     * Returns true if the class has Lombok annotations and the field name matches
     * a known generated field name.
     */
    public static boolean isLombokGeneratedField(
            ClassOrInterfaceDeclaration cls,
            FieldDeclaration field) {
        if (!hasLombokFieldGenerators(cls)) {
            return false;
        }

        String fieldName = field.getVariables().get(0).getNameAsString();
        for (AnnotationExpr ann : cls.getAnnotations()) {
            String annName = ann.getNameAsString();
            Set<String> generated = GENERATED_FIELDS.get(annName);
            if (generated != null && generated.contains(fieldName)) {
                return true;
            }
        }
        return false;
    }
}
